endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false               
      
multipart:
  maxFileSize: -1
  maxRequestSize: 1024Mb

amazon:
  aws:
    credentials:
      accessKey: AKIAJO7QEVD4VO77ZX7Q
      secretKey: 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 
  s3:
    bucket:
      name: cultur-assets-development
      region: us-west-2
    defaultBucket:
      name: cultur-assets-development
      region: us-west-2
      path: uploads/photos/
    paths:
      separator: /
      events: event/photo/
   
hystrix:
  command:
    default:
      requestLog: http://uatcsl.preprod.sea.amway.net
      enabled: false
    upload:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true
        timeout:
          enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 2000
        errorThresholdPercentage: 50
        requestVolumeThreshold: 10
      metrics:
        rollingStats:
          timeInMilliseconds: 180000
    download:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true
        timeout:
          enabled: true
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 2000
        errorThresholdPercentage: 50
        requestVolumeThreshold: 10
      metrics:
        rollingStats:
          timeInMilliseconds: 180000          
  threadpool:
    s3bucket:
      coreSize: 100
      maximumSize: 100
      queueSizeRejectionThreshold: 5
      keepAliveTimeMinutes: 1
      allowMaximumSizeToDivergeFromCoreSize: true
      metrics:
        rollingStats:
          timeInMilliseconds: 18000

